[tool.black]
target-version =  ['py36', 'py37', 'py38']
include = '''
^/(
    setup.py
    | freeze/pyinstaller.spec
    | src/ssst/.*\.pyi?
)$
'''
exclude = ''

[build-system]
requires = [
    "setuptools >= 51.0.0",
    "wheel >= 0.36.2",
]
build-backend = "setuptools.build_meta"
